Repository ituglib/gmake, pull requests merged in 2020-10, with the labels that each got.

#6 Fix #5 for Code Analysis
  Makefile
  file.c
  glob/glob.c
  signame.c
  tandem.c
  tandem_ext.c
Labels: CLA-Approved

#7 Updated arscan.c to support case-insensitive scan.
  arscan.c
Labels: CLA-Approved

#11 Removed -Wallow_cplusplus_comments and change optimization to -O2
  Makefile.NSE.OSS
  Makefile.NSE.Win
  Makefile.NSX.OSS
  Makefile.NSX.Win
  makein
Labels: CLA-Approved

#12 Using tag and committer date to compute VPROC
  Makefile
  Makefile.NSE.OSS
  Makefile.NSE.Win
  Makefile.NSX.OSS
  Makefile.NSX.Win
  main.c
  makein
  ver.c
  version.c
  version.sh
Labels: CLA-Approved

#13 Fix typo in README
  README
Labels: CLA-Approved

#17 Create pull_request_template.md
  CONTRIBUTING.md
  policies/cla.html
  pull_request_template.md
Labels: CLA-Approved, documentation

#18 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#22 Update Jenkinsfiles to pull tags in support of new packaging.
  Jenkinsfile.cgnac1
  Jenkinsfile.hpitug
Labels: CLA-Approved-Trivial

#26 Replaced fopen with FILE_GETINFOBYNAME_ for existence checks.
  dir.c
Labels: CLA-Approved

#32 Fixed define pass-off when starting child processes.
  tandem.c
Labels: CLA-Approved-Trivial

#34 Added GHOME to the remote phase in Jenkinsfile.cgnac1
  Jenkinsfile.cgnac1
Labels: CLA-Approved-Trivial

#36 Changed PROCESS_LAUNCH_ to use correct DEFINE MODE settings.
  tandem.c
Labels: CLA-Approved-Trivial
